#!/usr/bin/env bash
# Regenerates src/gui/win32/resources/icon_bmp.h (the GUI's embedded
# application icon) from namebreak.png at the repository root. Needs ImageMagick (`convert`) and
# `xxd`. Each icon size Windows may ask for is rendered separately, straight
# from the full-resolution original (never by shrinking a smaller copy - that
# is what made the small sizes blurry), with sharpening/contrast tuned per size
# and a tighter crop around the goggle lens for the tiniest one.
set -euo pipefail
cd "$(dirname "$0")"
SRC=../../namebreak.png
OUT=../src/gui/win32/resources/icon_bmp.h
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# render SIZE CROP UNSHARP CONTRAST SATURATION
render() {
  convert "$SRC" -crop "$2" +repage -colorspace RGB -filter Lanczos -resize "$1x$1" -colorspace sRGB \
          -sigmoidal-contrast "$4,50%" -modulate "100,$5" -unsharp "$3" "BMP3:$TMP/icon$1.bmp"
}
render 16 520x520+800+250 0x0.6+1.4+0 2.5 108
render 24 640x640+680+190 0x0.7+1.2+0 2.5 108
render 32 640x640+680+190 0x0.7+1.2+0 2.5 108
render 48 640x640+680+190 0x0.8+1.0+0 2   106
render 64 640x640+680+190 0x0.9+0.8+0 2   105
render 96 640x640+680+190 0x0.9+0.8+0 2   105

{
  cat <<'HEADER'
// GENERATED by scripts/make_icon_header.sh from namebreak.png (at the
// repository root) - do not edit.
//
// Embedded application icon for the GUI (app_icons.cpp: window, taskbar and
// tray icons): a crop of the fish's head (eye, goggle lens and a few teeth - the
// part that still reads at small sizes), pre-rendered at each size Windows may
// ask for as a 24-bit bottom-up BMP with its BITMAPFILEHEADER. Embedded as
// bytes (no .rc / resource compiler, no image-decoder dependency); the GUI
// picks the smallest one that is at least as large as the size requested.
#ifndef NAMEBREAK_GUI_WIN32_RESOURCES_ICON_BMP_H
#define NAMEBREAK_GUI_WIN32_RESOURCES_ICON_BMP_H

HEADER
  for s in 16 24 32 48 64 96; do
    echo "static const unsigned char kIconBmp$s[] = {"
    xxd -i < "$TMP/icon$s.bmp"
    echo "};"
    echo
  done
  cat <<'FOOTER'
struct IconImage {
    int size; // width == height, in pixels
    const unsigned char* bmp;
};

// Ascending by size.
static const IconImage kIconImages[] = {
    {16, kIconBmp16}, {24, kIconBmp24}, {32, kIconBmp32}, {48, kIconBmp48}, {64, kIconBmp64}, {96, kIconBmp96},
};

#endif // NAMEBREAK_GUI_WIN32_RESOURCES_ICON_BMP_H
FOOTER
} > "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
